# -----------------------------------------------------
# Config file :
# - input/ouput dir
# - source/target languages
#
# 11 novembre 2021
# @author : jeremylhour
# -----------------------------------------------------
DIR:
  IN: data/raw/               # input files location
  OUT: data/translated/       # output files location

LANGUAGES:
  SRC: fr                     # source language
  TGT: en                     # target language